title: Jessica's Art and Development
author: Jessica Kincaid
email: 4j.kincaid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Becoming an artist and learning to develop sites is a marathon. I'm still walking and running, learning as I go. 
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
